using System;

namespace Codemasters.F1_2020
{
    public enum Driver
    {
        CarlosSainz = 0,
        DaniilKvyat = 1,
        DanielRicciardo = 2,
        KimiRaikkonen = 6,
        LewisHamilton = 7,
        MaxVerstappen = 9,
        NicoHulkenburg = 10,
        KevinMagnussen = 11,
        RomainGrosjean = 12,
        SebastianVettel = 13,
        SergioPerez = 14,
        ValtteriBottas = 15,
        EstebanOcon = 17,
        LanceStroll = 19,
        ArronBarnes = 20,
        MartinGiles = 21,
        AlexMurray = 22,
        LucasRoth = 23,
        IgorCorreia = 24,
        SophieLevasseur = 25,
        JonasSchiffer = 26,
        AlainForest = 27,
        JayLetourneau = 28,
        EstoSaari = 29,
        YasarAtiyeh = 30,
        CallistoCalabresi = 31,
        NaotaIzum = 32,
        HowardClarke = 33,
        WilheimKaufmann = 34,
        MarieLaursen = 35,
        FlavioNieves = 36,
        PeterBelousov = 37,
        KlimekMichalski = 38,
        SantiagoMoreno = 39,
        BenjaminCoppens = 40,
        NoahVisser = 41,
        GertWaldmuller = 42,
        JulianQuesada = 43,
        DanielJones = 44,
        ArtemMarkelov = 45,
        TadasukeMakino = 46,
        SeanGelael = 47,
        NyckDeVries = 48,
        JackAitken = 49,
        GeorgeRussell = 50,
        MaximilianGünther = 51,
        NireiFukuzumi = 52,
        LucaGhiotto = 53,
        LandoNorris = 54,
        SergioSetteCamara = 55,
        LouisDeletraz = 56,
        AntonioFuoco = 57,
        CharlesLeclerc = 58,
        PierreGasly = 59,
        AlexanderAlbon = 62,
        NicholasLatifi = 63,
        DorianBoccolacci = 64,
        NikoKari = 65,
        RobertoMerhi = 66,
        ArjunMaini = 67,
        AlessioLorandi = 68,
        RubenMeijer = 69,
        RashidNair = 70,
        JackTremblay = 71,
        AntonioGiovinazzi = 74,
        RobertKubica = 75,
        NobuharuMatsushita = 78,
        NikitaMazepin = 79,
        GuanyaZhou = 80,
        MickSchumacher = 81,
        CallumIlott = 82,
        JuanManuelCorrea = 83,
        JordanKing = 84,
        MahaveerRaghunathan = 85,
        TatianaCalderon = 86,
        AnthoineHubert = 87,
        GuilianoAlesi = 88,
        RalphBoschung = 89,
    }

}